# Generated by Django 3.1.5 on 2021-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progreso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='apellido',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
    ]
